### ISSUE TITLE
Strapi: missing `APP_KEYS` from autogenerated `.environment` file

### ISSUE THREAD

**Issue by flovntp** [platformsh/cli#150] opened 2023-11-08 10:47 UTC
We are still missing a strapi specific environment variable `APP_KEYS`
```
export APP_KEYS="toBeModified1,toBeModified2"
```

Could you please add it to the `project:init` command ?

**Comment by akalipetis** [comment] 2023-11-21 16:35
This is a duplicate of https://github.com/platformsh/platformify/issues/178

**Closed by akalipetis** 2023-11-21 16:35 UTC
